### ISSUE TITLE
ModuleNotFoundError: No module named 'greeneye.protocol'

### ISSUE THREAD

**Issue by rogerfar** [jkeljo/greeneye-monitor#10]
I tried running dump_packets.py after installing this project from source, but when I run it I get the following error:

```
Traceback (most recent call last):
  File "C:\Projects\greeneye-monitor-3.0.1\dump_packets.py", line 10, in <module>
    from greeneye.monitor import (
  File "C:\Projects\greeneye-monitor-3.0.1\greeneye\__init__.py", line 1, in <module>
    from .monitor import Monitors
  File "C:\Projects\greeneye-monitor-3.0.1\greeneye\monitor.py", line 25, in <module>
    from .protocol import GemProtocol
ModuleNotFoundError: No module named 'greeneye.protocol'
```
I installed the `siobrultech-protocols` package.

Could it be because I'm trying to run it on Windows?

**Comment by sdwilsh** [comment]
This is almost certainly because this script wasn't updated after the change to use https://github.com/sdwilsh/siobrultech-protocols

**Comment by jkeljo** [comment]
Heh, nope, looks like I've got an untracked file in my local repo. Fixed now.
