### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by ptr727** [jkeljo/greeneye-monitor#3]
Hi, I finally got around to trying HA again, using version 0.105.4.

On every startup I get an error like this:
```
2020-02-15 10:29:26 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 424, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/greeneye_monitor/sensor.py", line 312, in state
    if not self._monitor.voltage:
AttributeError: 'NoneType' object has no attribute 'voltage'
2020-02-15 10:29:26 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 424, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/greeneye_monitor/sensor.py", line 312, in state
    if not self._monitor.voltage:
AttributeError: 'NoneType' object has no attribute 'voltage'
```

My settings look like this:
```
logger:
  default: warning
  logs:
    homeassistant.components.greeneye: debug
    greeneye.monitor: debug
    greeneye.streams: debug   

greeneye_monitor:
  port: 8000
  monitors:
    - serial_number: "01000181"
      voltage:
        - number: 1
          name: upstairs_volts
      channels:
        - number: 1
          name: gem_1_channel_1
        - number: 2
          name: gem_1_channel_2
    - serial_number: "01000172"
      voltage:
        - number: 1
          name: downstairs_volts
      pulse_counters:
        - number: 3
          name: gem_2_water
          counted_quantity: "gal"
          counted_quantity_per_pulse: 10
          time_unit: "min"
        - number: 4
          name: gem_2_gas
          counted_quantity: "cuft"
          counted_quantity_per_pulse: 10
          time_unit: "min"
```

I am getting GEM data:
```
2020-02-15 10:29:26 INFO (MainThread) [greeneye.streams] Connection from ('192.168.1.243', 2528)
2020-02-15 10:29:26 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.243', 2528)
2020-02-15 10:29:26 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (255 bytes)
2020-02-15 10:29:26 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.243', 2528)
2020-02-15 10:29:26 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (510 bytes)
2020-02-15 10:29:26 DEBUG (MainThread) [greeneye.streams] Received 115 bytes from ('192.168.1.243', 2528)
2020-02-15 10:29:26 DEBUG (MainThread) [greeneye.streams] Parsed one BIN48-NET-TIME packet.
2020-02-15 10:29:26 DEBUG (MainThread) [greeneye.streams] Parsed 1 packet from ('192.168.1.243', 2528)
2020-02-15 10:29:26 INFO (MainThread) [greeneye.monitor] Discovered new monitor: 1000172
2020-02-15 10:29:26 ERROR (MainThread) [homeassistant.components.deconz] Error connecting to deCONZ gateway at 192.168.1.28
2020-02-15 10:29:26 WARNING (MainThread) [homeassistant.config_entries] Config entry for deconz not ready yet. Retrying in 5 seconds.
2020-02-15 10:29:29 INFO (MainThread) [greeneye.streams] Connection closed from ('192.168.1.243', 2528)
2020-02-15 10:29:30 INFO (MainThread) [greeneye.streams] Connection from ('192.168.1.148', 2553)
2020-02-15 10:29:30 DEBUG (MainThread) [greeneye.streams] Received 25 bytes from ('192.168.1.148', 2553)
2020-02-15 10:29:30 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (25 bytes)
2020-02-15 10:29:30 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.148', 2553)
2020-02-15 10:29:30 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (280 bytes)
2020-02-15 10:29:30 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.148', 2553)
2020-02-15 10:29:30 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (535 bytes)
2020-02-15 10:29:33 INFO (MainThread) [greeneye.streams] Connection closed from ('192.168.1.148', 2553)
2020-02-15 10:29:35 ERROR (MainThread) [homeassistant.components.deconz] Error connecting to deCONZ gateway at 192.168.1.28
2020-02-15 10:29:35 WARNING (MainThread) [homeassistant.config_entries] Config entry for deconz not ready yet. Retrying in 10 seconds.
2020-02-15 10:29:36 INFO (MainThread) [greeneye.streams] Connection from ('192.168.1.243', 2529)
2020-02-15 10:29:36 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.243', 2529)
2020-02-15 10:29:36 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (255 bytes)
2020-02-15 10:29:36 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.243', 2529)
2020-02-15 10:29:36 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (510 bytes)
2020-02-15 10:29:36 DEBUG (MainThread) [greeneye.streams] Received 115 bytes from ('192.168.1.243', 2529)
2020-02-15 10:29:36 DEBUG (MainThread) [greeneye.streams] Parsed one BIN48-NET-TIME packet.
2020-02-15 10:29:36 DEBUG (MainThread) [greeneye.streams] Parsed 1 packet from ('192.168.1.243', 2529)
2020-02-15 10:29:39 INFO (MainThread) [greeneye.streams] Connection closed from ('192.168.1.243', 2529)
2020-02-15 10:29:40 INFO (MainThread) [greeneye.streams] Connection from ('192.168.1.148', 2554)
2020-02-15 10:29:40 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.148', 2554)
2020-02-15 10:29:40 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (255 bytes)
2020-02-15 10:29:40 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.148', 2554)
2020-02-15 10:29:40 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (510 bytes)
2020-02-15 10:29:40 DEBUG (MainThread) [greeneye.streams] Received 115 bytes from ('192.168.1.148', 2554)
2020-02-15 10:29:40 DEBUG (MainThread) [greeneye.streams] Parsed one BIN48-NET-TIME packet.
2020-02-15 10:29:40 DEBUG (MainThread) [greeneye.streams] Parsed 1 packet from ('192.168.1.148', 2554)
2020-02-15 10:29:40 INFO (MainThread) [greeneye.monitor] Discovered new monitor: 1000181
2020-02-15 10:29:43 INFO (MainThread) [greeneye.streams] Connection closed from ('192.168.1.148', 2554)
2020-02-15 10:29:46 INFO (MainThread) [greeneye.streams] Connection from ('192.168.1.243', 2530)
2020-02-15 10:29:46 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.243', 2530)
2020-02-15 10:29:46 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (255 bytes)
2020-02-15 10:29:46 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.243', 2530)
2020-02-15 10:29:46 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (510 bytes)
2020-02-15 10:29:46 DEBUG (MainThread) [greeneye.streams] Received 115 bytes from ('192.168.1.243', 2530)
2020-02-15 10:29:46 DEBUG (MainThread) [greeneye.streams] Parsed one BIN48-NET-TIME packet.
2020-02-15 10:29:46 DEBUG (MainThread) [greeneye.streams] Parsed 1 packet from ('192.168.1.243', 2530)
2020-02-15 10:29:49 ERROR (MainThread) [homeassistant.components.deconz] Error connecting to deCONZ gateway at 192.168.1.28
2020-02-15 10:29:49 WARNING (MainThread) [homeassistant.config_entries] Config entry for deconz not ready yet. Retrying in 20 seconds.
2020-02-15 10:29:49 INFO (MainThread) [greeneye.streams] Connection closed from ('192.168.1.243', 2530)
2020-02-15 10:29:50 INFO (MainThread) [greeneye.streams] Connection from ('192.168.1.148', 2555)
2020-02-15 10:29:50 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.148', 2555)
2020-02-15 10:29:50 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (255 bytes)
2020-02-15 10:29:50 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.148', 2555)
2020-02-15 10:29:50 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (510 bytes)
2020-02-15 10:29:50 DEBUG (MainThread) [greeneye.streams] Received 115 bytes from ('192.168.1.148', 2555)
2020-02-15 10:29:50 DEBUG (MainThread) [greeneye.streams] Parsed one BIN48-NET-TIME packet.
2020-02-15 10:29:50 DEBUG (MainThread) [greeneye.streams] Parsed 1 packet from ('192.168.1.148', 2555)
2020-02-15 10:29:53 INFO (MainThread) [greeneye.streams] Connection closed from ('192.168.1.148', 2555)
2020-02-15 10:29:56 INFO (MainThread) [greeneye.streams] Connection from ('192.168.1.243', 2531)
2020-02-15 10:29:56 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.243', 2531)
2020-02-15 10:29:56 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (255 bytes)
2020-02-15 10:29:56 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.243', 2531)
2020-02-15 10:29:56 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (510 bytes)
2020-02-15 10:29:56 DEBUG (MainThread) [greeneye.streams] Received 115 bytes from ('192.168.1.243', 2531)
2020-02-15 10:29:56 DEBUG (MainThread) [greeneye.streams] Parsed one BIN48-NET-TIME packet.
2020-02-15 10:29:56 DEBUG (MainThread) [greeneye.streams] Parsed 1 packet from ('192.168.1.243', 2531)
2020-02-15 10:29:59 INFO (MainThread) [greeneye.streams] Connection closed from ('192.168.1.243', 2531)
2020-02-15 10:30:00 INFO (MainThread) [greeneye.streams] Connection from ('192.168.1.148', 2556)
2020-02-15 10:30:00 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.148', 2556)
2020-02-15 10:30:00 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (255 bytes)
2020-02-15 10:30:00 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.148', 2556)
2020-02-15 10:30:00 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (510 bytes)
2020-02-15 10:30:00 DEBUG (MainThread) [greeneye.streams] Received 115 bytes from ('192.168.1.148', 2556)
2020-02-15 10:30:00 DEBUG (MainThread) [greeneye.streams] Parsed one BIN48-NET-TIME packet.
2020-02-15 10:30:00 DEBUG (MainThread) [greeneye.streams] Parsed 1 packet from ('192.168.1.148', 2556)
2020-02-15 10:30:03 INFO (MainThread) [greeneye.streams] Connection closed from ('192.168.1.148', 2556)
2020-02-15 10:30:06 INFO (MainThread) [greeneye.streams] Connection from ('192.168.1.243', 2532)
2020-02-15 10:30:06 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.243', 2532)
2020-02-15 10:30:06 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (255 bytes)
2020-02-15 10:30:06 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.243', 2532)
2020-02-15 10:30:06 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (510 bytes)
2020-02-15 10:30:06 DEBUG (MainThread) [greeneye.streams] Received 115 bytes from ('192.168.1.243', 2532)
2020-02-15 10:30:06 DEBUG (MainThread) [greeneye.streams] Parsed one BIN48-NET-TIME packet.
2020-02-15 10:30:06 DEBUG (MainThread) [greeneye.streams] Parsed 1 packet from ('192.168.1.243', 2532)
2020-02-15 10:30:09 INFO (MainThread) [greeneye.streams] Connection closed from ('192.168.1.243', 2532)
2020-02-15 10:30:10 INFO (MainThread) [greeneye.streams] Connection from ('192.168.1.148', 2557)
2020-02-15 10:30:10 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.148', 2557)
2020-02-15 10:30:10 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (255 bytes)
2020-02-15 10:30:10 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.148', 2557)
2020-02-15 10:30:10 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (510 bytes)
2020-02-15 10:30:10 DEBUG (MainThread) [greeneye.streams] Received 115 bytes from ('192.168.1.148', 2557)
2020-02-15 10:30:10 DEBUG (MainThread) [greeneye.streams] Parsed one BIN48-NET-TIME packet.
2020-02-15 10:30:10 DEBUG (MainThread) [greeneye.streams] Parsed 1 packet from ('192.168.1.148', 2557)
2020-02-15 10:30:13 ERROR (MainThread) [homeassistant.components.deconz] Error connecting to deCONZ gateway at 192.168.1.28
2020-02-15 10:30:13 WARNING (MainThread) [homeassistant.config_entries] Config entry for deconz not ready yet. Retrying in 40 seconds.
2020-02-15 10:30:13 INFO (MainThread) [greeneye.streams] Connection closed from ('192.168.1.148', 2557)
2020-02-15 10:30:16 INFO (MainThread) [greeneye.streams] Connection from ('192.168.1.243', 2533)
2020-02-15 10:30:16 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.243', 2533)
2020-02-15 10:30:16 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (255 bytes)
2020-02-15 10:30:16 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.243', 2533)
2020-02-15 10:30:16 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (510 bytes)
2020-02-15 10:30:16 DEBUG (MainThread) [greeneye.streams] Received 115 bytes from ('192.168.1.243', 2533)
2020-02-15 10:30:16 DEBUG (MainThread) [greeneye.streams] Parsed one BIN48-NET-TIME packet.
2020-02-15 10:30:16 DEBUG (MainThread) [greeneye.streams] Parsed 1 packet from ('192.168.1.243', 2533)
2020-02-15 10:30:19 INFO (MainThread) [greeneye.streams] Connection closed from ('192.168.1.243', 2533)
2020-02-15 10:30:20 INFO (MainThread) [greeneye.streams] Connection from ('192.168.1.148', 2558)
2020-02-15 10:30:20 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.148', 2558)
2020-02-15 10:30:20 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (255 bytes)
2020-02-15 10:30:20 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.148', 2558)
2020-02-15 10:30:20 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (510 bytes)
2020-02-15 10:30:20 DEBUG (MainThread) [greeneye.streams] Received 115 bytes from ('192.168.1.148', 2558)
2020-02-15 10:30:20 DEBUG (MainThread) [greeneye.streams] Parsed one BIN48-NET-TIME packet.
2020-02-15 10:30:20 DEBUG (MainThread) [greeneye.streams] Parsed 1 packet from ('192.168.1.148', 2558)
2020-02-15 10:30:23 INFO (MainThread) [greeneye.streams] Connection closed from ('192.168.1.148', 2558)
2020-02-15 10:30:26 INFO (MainThread) [greeneye.streams] Connection from ('192.168.1.243', 2534)
2020-02-15 10:30:26 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.243', 2534)
2020-02-15 10:30:26 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (255 bytes)
2020-02-15 10:30:26 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.243', 2534)
2020-02-15 10:30:26 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (510 bytes)
2020-02-15 10:30:26 DEBUG (MainThread) [greeneye.streams] Received 115 bytes from ('192.168.1.243', 2534)
2020-02-15 10:30:26 DEBUG (MainThread) [greeneye.streams] Parsed one BIN48-NET-TIME packet.
2020-02-15 10:30:26 DEBUG (MainThread) [greeneye.streams] Parsed 1 packet from ('192.168.1.243', 2534)
2020-02-15 10:30:30 INFO (MainThread) [greeneye.streams] Connection closed from ('192.168.1.243', 2534)
2020-02-15 10:30:30 INFO (MainThread) [greeneye.streams] Connection from ('192.168.1.148', 2559)
2020-02-15 10:30:30 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.148', 2559)
2020-02-15 10:30:30 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (255 bytes)
2020-02-15 10:30:30 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.148', 2559)
2020-02-15 10:30:30 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (510 bytes)
2020-02-15 10:30:30 DEBUG (MainThread) [greeneye.streams] Received 115 bytes from ('192.168.1.148', 2559)
2020-02-15 10:30:30 DEBUG (MainThread) [greeneye.streams] Parsed one BIN48-NET-TIME packet.
2020-02-15 10:30:30 DEBUG (MainThread) [greeneye.streams] Parsed 1 packet from ('192.168.1.148', 2559)
2020-02-15 10:30:33 INFO (MainThread) [greeneye.streams] Connection closed from ('192.168.1.148', 2559)
2020-02-15 10:30:36 INFO (MainThread) [greeneye.streams] Connection from ('192.168.1.243', 2535)
2020-02-15 10:30:36 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.243', 2535)
2020-02-15 10:30:36 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (255 bytes)
2020-02-15 10:30:36 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.243', 2535)
2020-02-15 10:30:36 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (510 bytes)
2020-02-15 10:30:36 DEBUG (MainThread) [greeneye.streams] Received 115 bytes from ('192.168.1.243', 2535)
2020-02-15 10:30:36 DEBUG (MainThread) [greeneye.streams] Parsed one BIN48-NET-TIME packet.
2020-02-15 10:30:36 DEBUG (MainThread) [greeneye.streams] Parsed 1 packet from ('192.168.1.243', 2535)
2020-02-15 10:30:40 INFO (MainThread) [greeneye.streams] Connection closed from ('192.168.1.243', 2535)
2020-02-15 10:30:40 INFO (MainThread) [greeneye.streams] Connection from ('192.168.1.148', 2560)
2020-02-15 10:30:40 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.148', 2560)
2020-02-15 10:30:40 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (255 bytes)
2020-02-15 10:30:40 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.148', 2560)
2020-02-15 10:30:40 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (510 bytes)
2020-02-15 10:30:40 DEBUG (MainThread) [greeneye.streams] Received 115 bytes from ('192.168.1.148', 2560)
2020-02-15 10:30:40 DEBUG (MainThread) [greeneye.streams] Parsed one BIN48-NET-TIME packet.
2020-02-15 10:30:40 DEBUG (MainThread) [greeneye.streams] Parsed 1 packet from ('192.168.1.148', 2560)
2020-02-15 10:30:43 INFO (MainThread) [greeneye.streams] Connection closed from ('192.168.1.148', 2560)
2020-02-15 10:30:46 INFO (MainThread) [greeneye.streams] Connection from ('192.168.1.243', 2536)
2020-02-15 10:30:46 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.243', 2536)
2020-02-15 10:30:46 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (255 bytes)
2020-02-15 10:30:46 DEBUG (MainThread) [greeneye.streams] Received 255 bytes from ('192.168.1.243', 2536)
2020-02-15 10:30:46 DEBUG (MainThread) [greeneye.streams] Not enough data in buffer yet (510 bytes)
```

**Comment by jkeljo** [comment]
That looks like a bug in the voltage support that somebody added in HA...
it should be checking for self._sensor is None rather than
self._sensor.voltage. Mind creating an issue over there? I’ll probably be
the one fixing it, but it’ll track better that way.

**Comment by ptr727** [comment]
Done, thx.
https://github.com/home-assistant/home-assistant/issues/31870

**Comment by ptr727** [comment]
I noticed a second problem where my one GEM updates the voltage graph as expected every 10s, but the second GEM's voltage data is very sporadic, with large gaps up to an hour where no data is recorded.

Per the debug log both GEM's are reporting in at about the same rate, and I verified this with my standalone echo utility, so I don't think it is a GEM issue.

I turned on debug logging and will run overnight, maybe something will show in the logs.

Could this error possibly affect the operation if multiple GEM's are used?

**Comment by ptr727** [comment]
From the logs I observed that both GEM's send packets at expected intervals.
But as expected only when a sensor value changes is the value sent to hass.

My one GEM has current sensors hooked up, and that one always reports a change to hass, including a voltage change.
My second GEM only has a temp probe and gas and water meter counters connected, that GEM rarely reports a change to hass.

It looks to me as if the voltage is only reported when another input value changes, i.e. changes in voltage is not reported. I expect all sensor inputs to report on changes, volts, temp, amp, counters.

That could explain the long gaps in reporting on my one GEM, only when the gas or water meter dry contacts trigger do I get voltage measurements reported.

E.g. no sensor change reported
```
2020-02-16 06:18:48 DEBUG (MainThread) [greeneye.streams] Parsed one BIN48-NET-TIME packet.
2020-02-16 06:18:48 DEBUG (MainThread) [greeneye.streams] Parsed 1 packet from ('192.168.1.243', 4004)
2020-02-16 06:18:51 DEBUG (SyncWorker_28) [homeassistant.components.august] Getting device activities
2020-02-16 06:18:51 INFO (MainThread) [greeneye.streams] Connection closed from ('192.168.1.243', 4004)
```

E.g. sensor change reported
```
2020-02-16 06:18:42 DEBUG (MainThread) [greeneye.streams] Parsed one BIN48-NET-TIME packet.
2020-02-16 06:18:42 DEBUG (MainThread) [greeneye.streams] Parsed 1 packet from ('192.168.1.148', 4003)
2020-02-16 06:18:42 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.channel_1, old_state=<state sensor.channel_1=0.13333333333333333; watt_seconds=12927640, unit_of_measurement=W, friendly_name=gem_1_channel_1, icon=mdi:flash @ 2020-02-16T06:18:27.282083-08:00>, new_state=<state sensor.channel_1=0.06666666666666667; watt_seconds=12927641, unit_of_measurement=W, friendly_name=gem_1_channel_1, icon=mdi:flash @ 2020-02-16T06:18:42.301150-08:00>>
2020-02-16 06:18:42 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.upstairs_volts, old_state=<state sensor.upstairs_volts=122.4; unit_of_measurement=V, friendly_name=gem_1_volts, icon=mdi:current-ac @ 2020-02-16T06:18:27.282896-08:00>, new_state=<state sensor.upstairs_volts=122.5; unit_of_measurement=V, friendly_name=gem_1_volts, icon=mdi:current-ac @ 2020-02-16T06:18:42.302503-08:00>>
2020-02-16 06:18:42 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.channel_2, old_state=<state sensor.channel_2=313.06666666666666; watt_seconds=6004262270, unit_of_measurement=W, friendly_name=gem_1_channel_2, icon=mdi:flash @ 2020-02-16T06:18:27.283640-08:00>, new_state=<state sensor.channel_2=263.53333333333336; watt_seconds=6004266223, unit_of_measurement=W, friendly_name=gem_1_channel_2, icon=mdi:flash @ 2020-02-16T06:18:42.303301-08:00>>
2020-02-16 06:18:42 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.22359329422032] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=sensor.channel_1, old_state=<state sensor.channel_1=0.13333333333333333; watt_seconds=12927640, unit_of_measurement=W, friendly_name=gem_1_channel_1, icon=mdi:flash @ 2020-02-16T06:18:27.282083-08:00>, new_state=<state sensor.channel_1=0.06666666666666667; watt_seconds=12927641, unit_of_measurement=W, friendly_name=gem_1_channel_1, icon=mdi:flash @ 2020-02-16T06:18:42.301150-08:00>>}
2020-02-16 06:18:42 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.22359329422032] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=sensor.upstairs_volts, old_state=<state sensor.upstairs_volts=122.4; unit_of_measurement=V, friendly_name=gem_1_volts, icon=mdi:current-ac @ 2020-02-16T06:18:27.282896-08:00>, new_state=<state sensor.upstairs_volts=122.5; unit_of_measurement=V, friendly_name=gem_1_volts, icon=mdi:current-ac @ 2020-02-16T06:18:42.302503-08:00>>}
2020-02-16 06:18:42 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.22359329422032] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=sensor.channel_2, old_state=<state sensor.channel_2=313.06666666666666; watt_seconds=6004262270, unit_of_measurement=W, friendly_name=gem_1_channel_2, icon=mdi:flash @ 2020-02-16T06:18:27.283640-08:00>, new_state=<state sensor.channel_2=263.53333333333336; watt_seconds=6004266223, unit_of_measurement=W, friendly_name=gem_1_channel_2, icon=mdi:flash @ 2020-02-16T06:18:42.303301-08:00>>}
2020-02-16 06:18:45 INFO (MainThread) [greeneye.streams] Connection closed from ('192.168.1.148', 4003)
```

**Comment by jkeljo** [comment]
Also a bug in the voltage support; it explicitly registered for
notifications of a current channel reporting rather than a packet coming in.

**Comment by ptr727** [comment]
Even more frustrating now that your change was benched for so long and then another now obviously buggy change got front of the line treatment.

As FYI, I noticed the temp docs do not match the example, see: https://github.com/home-assistant/home-assistant.io/issues/12099
And I'm not getting any temp readings reported in the graph, still investigating.

**Comment by ptr727** [comment]
An update on temp readings:
If I heat and cool the temp sensor I can see data recorded, but the reported temp is double the actual temp. The 2 byte raw reading needs to be divided by 2.0 to get the actual degC value, and a raw value of 512 (256 after division) indicates no sensor attached.

In summary, 3 issues; exception error on startup, no data update on voltage change, temp reports double actual value.

**Comment by jkeljo** [comment]
You'd reported the temperature issue earlier, and I forgot about it, my apologies. I've got PRs up for all of the issues mentioned in this thread:

- doc issue: https://github.com/home-assistant/home-assistant.io/pull/12102
- exception on startup & no data update: https://github.com/home-assistant/home-assistant/pull/31895
- temperatures doubled: https://github.com/home-assistant/home-assistant/pull/31896

I'm going to close this issue now; feel free to watch those PRs! I'm now listed as a codeowner for this component in HA, so hopefully the PRs will go reasonably quickly.

**Comment by ptr727** [comment]
Thank you, I appreciate your prompt response.
